### ISSUE TITLE
h2childchan: Model streams in HTTP/2 as child channels

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3667]
Progress to feature parity with current HTTP/2 API (please add entry if you notice something missing):
- [x] #4503 Child channels
- [ ] #4914 Separate frame-based message passing from child channels
- [x] #4503 Inbound flow control
- [x] #4941 Outbound flow control
- [x] #4503 RST_STREAM propagated to child channel
- [x] #4503 GOAWAY propagated to child channel
- [x] #4941 No premature child promise completion (in child's `doWrite` due to `ChannelOutboundBuffer` interaction pattern)
- [ ] Outgoing priority/weight
- [ ] Custom frame type support (https://tools.ietf.org/html/rfc7540#section-5.5)
- [ ] #4527 Send PUSH_PROMISE (server-side)
- [x] #4913 Start new streams (client-side)
- [x] #5199 Map from HTTP/2 (on the wire) to HTTP/1 (handlers)
- [ ] Map from HTTP/1 (on the wire) to HTTP/2 (handlers)
- Channel options:
  - [ ] `ALLOW_HALF_CLOSURE`
  - [ ] `AUTO_READ`
  - [ ] `MAX_MESSAGES_PER_READ`
  - [ ] `WRITE_BUFFER_{HIGH,LOW}_WATER_MARK`  
## Background

The HTTP/2 implementation is currently monolithic. It only has one
Http2FrameListener and that applies to all streams. It is generally necessary
to extend Http2ConnectionHandler in order to override onStreamError. This
prohibits mixing different HTTP/2 services on the same connection, something
that HTTP/2 is intended to do.

The HTTP/2 implementation is also not "normal Netty." It doesn't use the
channel for communicating incoming data or for receiving outgoing data (instead
methods). Flow control is different than isWritable and setAutoRead (instead
methods). Streams have their own attributes and those attributes are needed
frequently because there isn't another place for per-stream variables.

It seems that much of the functionality built around Channels has had to be
re-invented or will need to be re-invented in the coming future. This has made
the API of the HTTP/2 implementation large and substantially increases its
learning curve. It is also hard to use properly and there are a lot of moving
parts that many users won't want to care about. Such an API may be better for
advanced or high performance usages, though.

It also isn't possible to implement a handler (ChannelHandler, or some
specialized class) that functions with both HTTP/1 and HTTP/2, as the two have
completely different models of operation.
## High-level solution

To me, it seems like using child channels would improve the situation
dramatically. The basic idea is that every time a new stream is created, a new
Channel is created for it whose parent() is the originating channel. You would
then use normal ChannelHandlers for processing the stream.

If the child channel shares the same eventLoop as the parent, it looks to add
little overhead. Reads and writes take place immediately and effectively
function the same as they do today. The main cost I see us discussing is the
object allocation necessary for creating a message to pass to the Channel.
Note that we _don't_ need to create a message for each WINDOW_UPDATE and PING;
these sorts of frames can be handled within the HTTP/2 codec without exposing
to the application; we only need to pass headers and data.
## Proof-of-concept

I have developed a proof-of-concept (#3666), built on top of the current HTTP/2 APIs.
Unfortunately, EmbeddedChannel doesn't work well because it isn't integrated
into the event loop. Additionally, LocalChannel doesn't work well because the
implementation needs to construct a LocalServerChannel, a client LocalChannel,
and a server LocalChannel per stream, with each Channel requiring the previous
to be fully constructed before its own construction. It would also require some
way of obtaining a reference to the server LocalChannel, which seems doable but
a bit icky. Although I attempted to make a reusable Channel, it appeared that
the amount of code that could be reused was relatively small and largely
uninteresting while the price consistently increased.

Thus, the ChildChannel I've created is intended only for HTTP/2's usage. It was
based on LocalChannel and you can see it is relatively simple, but it still
looks a bit generic. I was mostly deterred by doWrite() which was surprisingly
hard to implement in a generic and extremely efficient way. Even if we are able
to reuse code now, I feared that integration with flow control would prevent us
from doing useful sharing in the future.

The ChildChannel is _not_ using the parent Channel for communicating with the
connection (other than determining the event loop to run with, which is
actually a bit broken but easy to fix). For the moment that seemed prudent as
it would perform better, and I worried that performance would be a high
concern. We can discuss whether we think we should use message passing via the
parent Channel for communicating with the connection. It would primarily mean
the ChildChannel would have to wrap or re-package any messages sent on the
child channel to include the stream id.

Mostly-appropriate flushing is already available in the implementation,
although not very well when using different event loops. If using the same
event loop, we may want to suppress any flushes during channelReadComplete
until after all the streams have been called, as we would generally expect
every stream notified in channelReadComplete to flush.
## Expectations for some future features:

Flow control: Flow control will be implemented by watching the queue between
the connection and the streams.

For the inbound direction, when a frame is read it will be considered consumed,
which is basically identical to Netty/TCP/Kernel interaction today. This does
mean flow control is more coarse than the API affords today, but the normal
case will be the same. Note that setAutoRead defaults to true, so flow control
is "disabled" by default.

For the outbound direction, I have do not yet have a clear design, but we will
provide isWritable and channelWritabilityChanged. I doubt it will be best to
implement these methods by utilizing the parent's methods, as that would easily
starve streams and is harder to calculate. I have some thoughts on the subject,
but they still require investigation.

Half-close: It seems Netty has only a weak conceptual model of half-closing, so
I'm doubting exposing stream half-closing as channel half-closing. Instead, I'm
expecting to need to include closure information in the messages sent on the
stream (like is done for HTTP).

Stream-level messages sent on the child channel: I've not yet figured out if we
should re-use the HTTP/1 messages for HTTP/2. If we choose some HTTP/2-specific
messages we could still easily create an adapter that converts between the two
message types to allow having "HTTP" handlers that work for both HTTP/1 and
HTTP/2. The main issue for using the same messages is (surprise!) headers. I do
think we only need messages for headers and data. Other than END_STREAM and
similar "details," it doesn't seem unreasonable to just send ByteBufs and
Http2Headers.

To send RST_STREAM: It may involve closing the channel, but that doesn't
provide a way to give a reason for the reset. Thus, I wouldn't be surprised if
we make "close the stream" send INTERNAL_ERROR/CANCEL and then have a message
to send the other. The errors that _may_ look useful for an application to send
are: INTERNAL_ERROR, REFUSED_STREAM, CANCEL, ENHANCE_YOUR_CALM,
INADEQUATE_SECURITY, and HTTP_1_1_REQUIRED (heh).

Providing error details from RST_STREAM or GOAWAY to a stream: I don't have too
many ideas, but we could have an event on the child channel before closing the
child channel.

Connection-level outbound things: like GO_AWAY and creating new streams, we can
have methods on our Http2 ChannelHandler or have messages be sent to the parent
_channel_. I would lean toward the parent channel in general as 1) every child
stream has access to the parent channel, so PUSH_PROMISE could be easy to
initiate, 2) it provides a mechanism for intercepting such messages, and 3) the
threading requirements are easy and clear.  However, creating new streams could
benefit from a method as we could return a ChannelFuture which allows accessing
Channel immediately (even before its ID has been allocated). Having to buffer
while waiting for a Channel can be quite bothersome and it would be convenient
to avoid.

Connection-level inbound things: it seems channel events would work well, at
least for GO_AWAY and priority/weight notifications.

@nmittler, @buchgr, @Scottmitch for HTTP/2 specifics

@normanmaurer, @trustin for the general approach and soundness in concept

**Comment by buchgr** [comment]
first! @ejona86 +1

**Comment by normanmaurer** [comment]
@ejona86 I really like the idea. :+1:

**Comment by Scottmitch** [comment]
@ejona86 - Sounds like a good idea to me.  As you pointed out there is a risk of object allocation and associated GC costs increasing but may be a nice compromise for a lot of use cases.

**Comment by nmittler** [comment]
@ejona86 +1 very cool!

**Comment by jroper** [comment]
+1

Child handlers seem to me to be the perfect level to do this at, since they support the bidirectional flow of data and back pressure, and would allow HTTP1 applications to use HTTP2 with only a small amount of modification - nesting the channel initialiser for their app another pipeline deeper.  I'm actually surprised this wasn't done from the outset.

If done right, this would allow the reuse of [Netty reactive streams](https://github.com/typesafehub/netty-reactive-streams) at all nesting levels, for example, you could have a publisher of HTTP2 stream child channels, publishers/subscribers of HTTP 2 messages that handle each of those channels, and publishers/subscribers of the bodies of HTTP requests/responses associated with each request/response.

I think it would make a lot of sense to have the http2 data objects extend the equivalent Netty `HttpObject` messages, such as `HttpContent` and `HttpMessage`.  It would also help to implement the same semantics in the current HTTP support where a full http request/response is one `HttpMessage` followed by zero to many `HttpContent`, where the last message in the object is a `LastHttpContent` (and it is possible for the first `HttpMessage` to also be a `LastHttpContent`).  This would be necessary for applications that implement proper streaming of request and response bodies (not just aggregating them into `FullHttpMessage`, which obviously does not work for large bodies) to be able to use the same handler for HTTP 1 and HTTP 2.

We are interested in this for Play Framework, and are willing to help both in reviewing and in implementation, where necessary.  Let me know if there's anything I can help with.

**Comment by ejona86** [comment]
@jroper, having the HTTP/2 data objects extend the equivalent HttpObject turned out to be cause problems, almost entirely due to how headers are done differently in HTTP/2 via Http2Headers. Converting to/from the HTTP/1 headers is possible, but not free. Thus, it seemed that HTTP/2 having its own objects and only convert when an application adds a special converting handler was appropriate.

**Comment by normanmaurer** [comment]
@ejona86 but would the idea of do stuff with child channels and ChannelHandler apply ? I kind of like the idea to not need to "learn" another api :)

**Comment by jroper** [comment]
That surprises me because as the HTTP 2 spec states, HTTP 2 only changes the wire protocol, not the semantics of HTTP messages. And it was certainly the intention of the HTTP 2 spec authors that HTTP 2 should, to existing HTTP 1.1 apps, be a transparent upgrade. If there's something wrong with Netty's HTTP 1 data modeling that prevents it from being used with HTTP 2, then that is probably something that should be addressed by fixing the data modelling, not by making a second model.

At the end of the day, HTTP 2 is going to take many years to become ubiquitous. Even if browsers support it today, there are many, many HTTP clients out there that will take years to catch up, which means most users are going to have to support both HTTP 1 and HTTP 2 for some time. Forcing most users to essentially write their HTTP server code twice is a huge usability problem, one that would call into question Netty's suitability for HTTP 2 at all. Personally, I would rather have a compatible but maybe less optimal HTTP 2 implementation in Netty 4.x, and then address the problems caused by the existing HTTP modeling in Netty 5.x, than have something that set all apps down the path of having to write their code twice.

**Comment by ejona86** [comment]
@normanmaurer, I thought the entire point of this issue was to do stuff in child channels and use ChannelHanlders, so I didn't reply to that part. It seemed like a continuation of the +1.

@jroper, it is true that HTTP/2 only changes the wire protocol. However, Netty works _with_ the wire protocol (like in the Matrix :-P) and tries to have very high efficiency. So in the HTTP/2 implementation there are restrictions/tweaks that make it more efficient, such as only lowercase header names are permitted.

Netty is too low-level for the HTTP/2 support to be a _transparent_ upgrade. However, that doesn't mean that it would have to be hard. It was a goal of mine to make it possible to easily use the same handler independent of whether HTTP/1 or HTTP/2 on the wire. The converter logic for HTTP/2 to HTTP/1 and vise versa is pretty well understood in Netty right now, so I have very few concerns about implementing such things.

**Comment by jroper** [comment]
@ejona86 That makes sense - indeed many wire level concerns do flow into application code when using Netty.

Perhaps this deserves a new issue - but - I can see there is some existing conversion logic, however it converts to/from `FullHttpMessage`.  When we put Play on top of HTTP/2, for example, we won't be able to use this, since Play must not buffer the full body because Play bodies are potentially infinitely long, could represent SSE events streams, etc.  Of course, as a framework, it is not a high cost for us to implement our APIs directly on top of both the HTTP/1 and HTTP/2 APIs.  But our preference is, for anything that may be useful for more than just us, not to do something that's just specific for us, but to implement it in a way that can be used by anyone.

So our preferred approach would be to write conversion logic that supports streaming request HTTP/2 bodies in a way that's transparent to HTTP/1 users directly in Netty.  Is this already being done or do you have plans to do this?

**Comment by nmittler** [comment]
@jroper The translation layer between HTTP/2 and HTTP/1.x is given by a combination of [HttpToHttp2ConnectionHandler](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/HttpToHttp2ConnectionHandler.java) and [InboundHttp2ToHttpAdapter](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java).  You can see how to construct a pipeline using these in the [tiles example](https://github.com/netty/netty/blob/f51465977e19e56026c15c7360fbdd211fbd44b0/example/src/main/java/io/netty/example/http2/tiles/Http2OrHttpHandler.java#L61).

**Comment by jroper** [comment]
@nmittler yes I saw that, but the problem is, it buffers the entire body into FullHttpMessage objects, so is not suitable for large body handling, and is unable to send bodies that don't fit in memory.

**Comment by nmittler** [comment]
@jroper FYI this just came up in #3946

**Comment by Scottmitch** [comment]
reminder https://github.com/netty/netty/pull/4503#discussion_r54444640: as part of the outbound flow controller work we should fix the interaction with `ChannelOutboundBuffer` so we don't have to complete promises before they are actually written in we are not in the correct event loop.

**Comment by ejona86** [comment]
@Scottmitch, the poor interaction with `ChannelOutboundBuffer` is the "No premature child promise completion (in child's doWrite)" in the checklist above. Feel free to reword it :)

**Comment by Scottmitch** [comment]
@ejona86 - I see. Thanks. I just added a snippet about `ChannelOutboundBuffer` for more context.
