### ISSUE TITLE
h2childchan: Channel Options

### ISSUE THREAD

**Issue by buchgr** [netty/netty#5753]
This issue is to track the channel options that HTTP/2 child channels need (yet) to support (as they are part of `ChannelConfig`).

- [x] `ALLOCATOR`
- [x] `AUTO_READ`
- [x] `AUTO_CLOSE` - deprecated, but supported (via `AbstractChannel`).
- [ ] `CONNECT_TIMEOUT_MILLIS` - See #5752
- [x] `MAX_MESSAGES_PER_READ`
- [x] `MESSAGE_SIZE_ESTIMATOR` - #5747 adds its own.
- [x] `RCVBUF_ALLOCATOR` - that one's kind of useless for our purposes, as we don't allocate `ByteBufs` on read. Afaik we are currently only using it for `MAX_MESSAGES_PER_READ`.
- [ ] `WRITE_BUFFER_WATER_MARK` - #5747 uses this option for the flow control. That interacts nicely with the `ChannelOutboundBuffer`, as well as `Channel.bytesUntil(Un)Writable()`. Low and high watermark are always equal. A user can access the watermark via a getter, but **not set it.**
- [x] `WRITE_SPIN_COUNT` - Useless for our purposes?

Issue #3667 also mentions the option `ALLOW_HALF_CLOSURE`. We are carrying `END_STREAM` on the `Http2StreamFrame` objects. I don't think we need it.

I would suggest for options that are not useful for the H2 child channel, the setter methods should just be noops and log a warning, that they have no effect. Thoughts?

cc: @ejona86

**Comment by normanmaurer** [comment]
@buchgr why not throw an exception if someone tries to use options that are not supported ?

**Comment by buchgr** [comment]
@normanmaurer I considered it, but thought it's not legal due to the [ChannelConfig](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelConfig.java#L43) interface?

**Comment by shiluotang** [comment]
@buchgr RuntimeException does not need throws clause on method signature. But users may not like it.

**Comment by normanmaurer** [comment]
@buchgr well I am a bit on the fence here... Often I think it is better to throw and not ignore. At least this will be very clear ;)

**Comment by buchgr** [comment]
@shiluotang I was refering to ` All {@link ChannelConfig} has the following options:`

@normanmaurer I am fine with `UnsupportedOperationException` if you are :-)

**Comment by normanmaurer** [comment]
Lets do it :)

**Comment by ejona86** [comment]
> Issue #3667 also mentions the option ALLOW_HALF_CLOSURE. We are carrying END_STREAM on the Http2StreamFrame objects. I don't think we need it.

Do consider the case where someone is using HTTP/1 messages and it is being converted to HTTP/2. I agree that the converter could convert the close() to a DATA(EOS=true), though. But it may be better to have the channel work "like normal". The half close part was not a big deal, but there were details that seemed like we should dig into them.

**Comment by buchgr** [comment]
@ejona86 

Interesting. So you are saying that if `ALLOW_HALF_CLOSURE` is enabled and `close()` is called on a child channel, the child channel and stream shouldn't be closed but a `DATA(EOS=true)` should be sent?  If `ALLOW_HALF_CLOSURE` is disabled and `close()` is called, the stream should be closed via a `RST_STREAM`?
