### ISSUE TITLE
Ensure compatibility with Android devices using Jelly Bean

### ISSUE THREAD

**Issue by CruzBishop** [netty/netty#699]
## Please do not assign this issue to a milestone!

Android does not use the standard Java virtual machine - Instead, it uses a custom implementation\* called Dalvik.
### Task list

**More tasks coming soon. I have to go to work, so don't have enough time to complete the list yet.**
#### Netty v3
- [ ] Initial build test
- [ ] Attempt to bind a basic echo server to a port
- [ ] Communicate with the echo server
- [ ] Attempt to load websites (Google, Github, Reddit, etc)
#### Netty v4
- [ ] Initial build test
- [ ] Attempt to bind a basic echo server to a port
- [ ] Communicate with the echo server
- [ ] Attempt to load websites (Google, Github, Reddit, etc)
  
  _Yeah, I know it's not _really_ a virtual machine. Just easier to understand this way_
